# Setup
title:               Shoji Yuen's site
tagline:             ''
description:         '<img width="100" src="/assets/images/papa2-small.JPG"/>'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Gems
plugins:
  - jekyll-paginate
  - jekyll-polyglot

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

#
languages: ["en", "ja"]
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css", "public"]
parallel_localization: false
