# Site settings
title: Shoji Yuen
email: ""
description: >-
  Shoji Yuen's personal homepage for research, teaching, projects, and notes.
baseurl: ""
url: "https://syuen1.github.io"
github_username: syuen1

header_pages:
  - publications.markdown
  - about.markdown

exclude:
  - index.markdown
  - vendor/
  - .bundle/
